---
platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.10
  - name: ubuntu-16.04
  - name: centos-7.2
  - name: debian-8.4
  - name: fedora-23
  - name: macosx-10.10
    provisioner:
      require_pip: true
      ansible_binary_path: /usr/local/bin
    driver:
      name: vagrant
      box: macosx-10.10
      provision: true
      vagrantfiles:
        - osx_vagrant.rb
      synced_folders:
        - [".", "/vagrant", "type: :rsync"]
  - name: macosx-10.11
    provisioner:
      require_pip: true
      ansible_binary_path: /usr/local/bin
    driver:
      name: vagrant
      box: macosx-10.10
      provision: true
      vagrantfiles:
        - osx_vagrant.rb
      synced_folders:
        - [".", "/vagrant", "type: :rsync"]

