---
driver:
  name: docker
  require_chef_omnibus: false
  username: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_sudo: false
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: debian-9.9

suites:
  - name: default
