---
- name: Register current login shell for {{ user }}
  command: >
    dscl . -read /Users/{{ user }} UserShell
  changed_when: false
  register: darwin_user_shell

- name: Set facts
  set_fact:
    user_home: "/Users/{{ user }}"
    user_shell: "{{ darwin_user_shell.stdout.split(' ')[1] }}"
